### ISSUE TITLE
Restart button doesn't work

### ISSUE THREAD

**Issue by jenzou** [jenzou/cs184-final-project#1]
It doesn't do anything; please investigate

**Comment by zzw96** [comment]
Found restart() method unimplemented in a few files. GLApplication.cpp, PBFApp.cpp

**Comment by zzw96** [comment]
Maybe we can just call runMainLoop() in GLApplication::restart()

**Comment by zzw96** [comment]
Resolved. See commit "FIX RESTART" in my branch.
