### ISSUE TITLE
Vorticity updated with corrective force

### ISSUE THREAD

**Issue by jenzou** [jenzou/cs184-final-project#4]
https://github.com/jenzou/Fluid-Simulator/blob/1aae1d9e98f2129fc1a912d2ac6e766c338f198b/simulator/code/Assignment2/ParticleSystem.cpp#L158

Why is the vorticity updated with the corrective force? Also, after the corrective force is calculated, shouldn't it be applied to the velocity?

**Comment by zzw96** [comment]
_Why is the vorticity updated with the corrective force?_
I tried adding vorticity_F as a new field in Particle.h, was failing. So just placing the value in W as a placeholder.

_Also, after the corrective force is calculated, shouldn't it be applied to the velocity?_
Took out the part which applies it cause it wasn't working, this way the demo would run sans vorticity.
