### ISSUE TITLE
Rigid bodies collisions

### ISSUE THREAD

**Issue by jenzou** [jenzou/cs184-final-project#8]
Add basic 3D objects which particles will collide with.

- Cube
- Pyramid
- Sphere
- Bunny

1) Create object surfaces
2) Add collision functions

**Comment by ilovecoding123456** [comment]
https://github.com/jenzou/Fluid-Simulator/blob/e7d7c472b5213b4f82ab3e4829417260ca1734a6/simulator/code/Assignment2/ParticleSystemLoader.cpp#L28-L32

@zchickenwang I added a line in the try block where I called `mesh->drawMesh()` from `GLMesh` on the bunny, but nothing appears on the screen. I assumed this function would draw; do you know if it should actually draw onto the screen (with revisions) or will I need to draw call GLEW functions myself like in `ParticleSystem::drawParticleSystem()`?

I started with the bunny, but seeing that `drawMesh()` doesn't work as intended, I was thinking of just creating 6 squares to make a cube (or calling built-in functions from libraries) and writing collision functions for the cube. What do you think?
